### PR TITLE
Migrate TravisCI to GitHub Actions

### PR DESCRIPTION
**Pull request by ybiquitous**
This change also adds Ruby 3.0 to the CI matrix.

See also <https://github.com/ruby/setup-ruby#matrix-of-ruby-versions>

### CODE REVIEW

**Comment by ybiquitous** [comment]
The new CI URLs can be updated after this PR merged.

https://github.com/GlobalNamesArchitecture/damerau-levenshtein/blob/d4e375479fbb8c6c8e36c705cec8c91cedf33704/README.md#L256-L257

**Comment by dimus** [comment]
thanks @ybiquitous very helpful

**Comment by dimus** [comment]
looks like something is missing, and CI fails atm. I will have to investigate, but sadly not soon, I can get back to it in 2 weeks or so. If you can try to fix the problem, it would be great @ybiquitous

**Comment by ybiquitous** [comment]
@dimus No worries! The problem seems like a RuboCop's issue. I'll look into it. 👍🏼

**Pull request merged**
